### PR TITLE
Make Rustic into a library

### PR DESCRIPTION
**Pull request by brandonros**

### CODE REVIEW

**Comment by mvanthoor** [comment]
@brandonros Thanks for the effort :) Making Rustic into a library was slated for version 5.0 (if/when I finish version 4's XBoard protocol and Texel tuner).

Note that I'd like to extract the entire engine part (not only the main function) from the library at some point. I will probably also move/rename some things during the process. I saw you forked Rustic for your chess_bot API, so a refactoring at my end will probably break your project if you just pull and use the latest version.

It is my intention to ultimately refactor Rustic into "librustic", with the engine Rustic being a seperate part. (I also intend to write a replacement for PicoChess some day, which will also require a chess-playing library.)

**Comment by brandonros** [comment]
@mvanthoor Do you expect there would be large performance gains from introducing a way to parallelize/multi-thread the iteration?

**Comment by mvanthoor** [comment]
@brandonros Yes, making the search parallel with Lazy SMP would gain an additional ~75 elo points per doubling of the computing speed. Going from 1 to 4 cores would thus add approximately 150 Elo on the CCRL list. However, there are much bigger and easier fish to fry:

- Adding null-move pruning adds ~80-100 Elo
- Adding a passed pawn recognition and defence (for Rustic, a pawn is a pawn, be it on c2 or a7) adds 100-120 points
- Adding a pawn hash and protecting the pawn structure adds ~50 Elo
- Making the evaluation tapered adds 200-300 (!) Elo, and this is already implemented; it works with tapered tables borrowed from other engines. Just the Textel Tuner needs to be finished.
- And many more.

You may not have noticed, but even though Rustic basically has no features except from the bare essentials to get it started, it is already 1800 in the CCRL Elo list. It is stronger than any other engine I have tested against it, given the same feature set in both engines. (Sometimes it's even stronger than engines with more features.) I expect Rustic to hit the following ratings:

- With Tapered and tuned evaluation: at least >=2000 (but I hope it will be 2050 or even 2100 if the function scales perfectly against engines others than the ones in my test set.)
- With Null Move pruning: >= 2100
- Pawn hash + pawn structure + passed pawns: >= 2270

That is +470 Elo over the current playing strength using features that are either easy to implement or already 70% done. I don't intend to start implementing Lazy SMP before Rustic reaches at least 3000 Elo on a single core on the CCRL list. Adding a neural network is on the list even beyond that, but I'll still retain the classic hand-crafted evaluation.

I've had a massive lack of time for programming on personal projects since 2022. The first thing I'd like to (finally) concentrate on for version 4.0 is adding more information to the rusctic-chess.org website book and finishing the XBoard protocol and Texel tuner. After that, it is relatively easy to just add more features and more evaluation terms; it's 'just' work and testing.

**Comment by brandonros** [comment]
@mvanthoor 

This might make you smile or laugh, hopefully.

1. I am also Dutch heritage, funny/small world.
2. I have no idea how to play chess/have never played a game of chess in my life. A new programming friend of mine asked if I liked to play and I told him I don't know how (I don't even know the name of the pieces/the rule moves/strategies, literally nothing) so I told him "let me set up a mini chess-bot and you try to play that"

Hope you do not think I am using it for cheating or something :)

You clearly know your stuff, very impressive. Wish I could help more on the chess side of things, let alone making chess meet programming (very difficult, all kudos to you)

I will not waste time with SMP. I wasn't sure if it would make `depth: 10+` process significantly faster. I was thinking `rayon.par_iter` dropin.

**Comment by mvanthoor** [comment]
@brandonros 

It's a small world indeed. What I have noticed is that MANY chess engines are written by Dutch, German and UK people. For some reason, that's a thing over here. Half of the regulars on the Talkchess forum are Dutch too.

With regard to playing chess; I've started playing chess at around 7 years old and ended up somewhere around 1850 Elo FIDE. Nowadays I swing between 1800 and 2000 depending on how much effort I put into playing games. I'll probably not improve until I do some serious study. With regard to chess study I'm lazy AF, because it's a hobby I only practice if I have too much time. (Which is not the case since 2022.)

With regard to chess programming: I've been tinkering with computers and (chess) software for decades and wrote my first (unstable...) engine in the 90's as a teenager. I liked Rust as a programming language and I wanted a project to use it for. Because I've always wanted to write a usable and stable chess engine, I decided to do that, 25 years after my first attempt.  It was relatively easy, to be honest; except for the magic bitboards and the transposition table (which isn't difficult conceptually, but one tiny mistake can render it useless), but the information internet made this doable after some study. The information on chess programming is super-splintered though, which is why I'm writing the stuff at rustic-chess.org.

And compared to people who are writing engines such as Stockfish, I still know nothing. They include optimizations to gain the last 3 Elo points that I won't even consider... I'll probably call the engine "finished" if it ever reaches 3200+ while running on a neural network.

Thanks for doing the first step of making a library out of the engine. I'll split off the engine part and the actual chess part at a later time. The library should only contain the chess functionality, not the engine itself.

You could try to write your own chess engine in Rust from scratch, on a simpler 10x12 array-based board. There are a few good tutorials on YouTube (Maksim Korzh, and BlueFever Software), and you'll learn all the chess rules by just doing this.

**Comment by brandonros** [comment]
@mvanthoor what depth would you run it at?

8 is pretty quick

10 is a little slow

**Comment by brandonros** [comment]
@mvanthoor just sharing with you as I just came across it https://obrhubr.org/chess-engine

**Pull request merged**
